services:
  web:
    container_name: node-web-contacts
    build:
      context: .
      dockerfile: ./infrastructure/docker/${NODE_ENV}/Dockerfile
    ports:
      - "${PORT}:3000"
    platform: "linux/amd64"
    image: node-web-contacts
    environment:
      - NODE_ENV=${NODE_ENV}
      - PATH_SSL_PRIVATE_KEY=${PATH_SSL_PRIVATE_KEY}
      - PATH_SSL_CERTIFICATE=${PATH_SSL_CERTIFICATE}
      - CDN_HOST=${CDN_HOST}
      - NODE_SSL_ENABLED=${NODE_SSL_ENABLED}
      - BASE_URL=${BASE_URL}
      - HUMAN=${HUMAN}
      - LOG_LEVEL=${LOG_LEVEL}
